### ISSUE TITLE
Support overriding the handler of defined queries

### ISSUE THREAD

**Issue by hqtoan94** [Mike-Gibson/mock-apollo-client#17]
There is an existing demand about writing integration test between UI components and services, and it might need the mock service to responsive response to adapt with the UI logic. So allowing override the request handlers might be really helpful in this case. So here is my suggestion for this:

### Suggestion:
- Create type `RequestHandlerOptions`:
```ts
export type RequestHandlerOptions = { overridable: boolean };
```
- Add a new parameter called: `handlerOptions`:
```ts
setRequestHandler(requestQuery: DocumentNode, handler: RequestHandler, handlerOptions: RequestHandlerOptions)
```
- Override requestHandler if `handlerOptions.overridable === true`:
```ts
if (this.requestHandlers[key] && !handlerOptions.overridable) {
      throw new Error(`Request handler already defined for query: ${print(requestQuery)}`);
}
```

Hope that we can have a discussion on this to find out the final solution and yeah, I can create a PR for that.
Thanks!

**Comment by Mike-Gibson** [comment]
Hi,

Thanks for using the library and for creating this issue.

Could you please explain a bit more about why you would want to replace a request handler?

There was a similar request in #10, which shows that when using a mock library (i.e. jest) you can have have the same request handler and configure it to return different results.

I'm not opposed to the idea of allowing replacements, but want to check it makes sense to add it.

**Comment by hqtoan94** [comment]
Yeah, actually I have missed that. So with one handler we could making different responses without overriding the handler.

Thank you @Mike-Gibson you saved my life :)..
Gonna close this Issue.

**Comment by Mike-Gibson** [comment]
Glad to have helped!

I might look at adding examples, or extending the readme with more info soon. This will be a good thing to include 🙂
