### ISSUE TITLE
Add subscriptions support to 0.x version

### ISSUE THREAD

**Issue by NataliaTepluhina** [Mike-Gibson/mock-apollo-client#28]
@Mike-Gibson would it be possible to adapt the change implemented in https://github.com/Mike-Gibson/mock-apollo-client/pull/26 to the 0.x version as well? We are still using Apollo Client 2.x so it would be great to test subscriptions there as well.

**Comment by Mike-Gibson** [comment]
Sorry for the delayed response.

I think it should be possible, yes.
I'll take a look at implementing it. I'll hopefully have some time this week or at the weekend.

**Comment by Mike-Gibson** [comment]
@NataliaTepluhina I've merged the changes to the 0.x branch and published version `0.7.0` to npm.

Give it a go and please let me know if you have any issues.

Thanks!

**Comment by NataliaTepluhina** [comment]
@Mike-Gibson thank you so much for fixing it! 🎉
