### ISSUE TITLE
Is there a way to reset the mockClient ?

### ISSUE THREAD

**Issue by rhishikeshj** [Mike-Gibson/mock-apollo-client#35]
I have a use-case where I am unit-testing a hook which imports the client from a different module.
Now I was able to mock this out and ensure that this results in importing the mockClient instead.

But now when I write multiple tests I want to reset / clear out the mock client object so that I can set request handlers for the same query again.

Is there some standard way of doing this ?

**Comment by Mike-Gibson** [comment]
Hi @rhishikeshj,

There's no way to reset the handlers for a mock client instance. I've not needed it before. Happy to add it if it would be useful, but when I've needed to change the response I've just used the same handler and a different response.

An example for jest - using `mockResolvedValue` to change the query result:

```typescript
let mockClient: MockApolloClient;
let requestHandler: jest.Mock;

beforeAll(() => {
  mockClient = createMockClient();

  requestHandler = jest.fn();

  mockClient.setRequestHandler(GET_DOG_QUERY, requestHandler);
});

it('renders the dog name and breed for a first result', async () => {
  requestHandler.mockResolvedValue({ data: { dog: { id: 1, name: 'Rufus', breed: 'Poodle' } } });

  const wrapper = mount(
    <ApolloProvider client={mockClient}>
      <Dog name="Rufus" />
    </ApolloProvider>
  );

  await new Promise(r => setTimeout(r, 0));
  wrapper.update();

  expect(wrapper.text()).toContain('Rufus is a Poodle');
});

it('renders the dog name and breed for a different result', async () => {
  requestHandler.mockResolvedValue({ data: { dog: { id: 1, name: 'Bob', breed: 'Labrador' } } });

  const wrapper = mount(
    <ApolloProvider client={mockClient}>
      <Dog name="Bob" />
    </ApolloProvider>
  );

  await new Promise(r => setTimeout(r, 0));
  wrapper.update();

  expect(wrapper.text()).toContain('Bob is a Labrador');
});
```

If this pattern doesn't work for you, or you'd prefer to have an explicit `clearRequestHandlers` method, I'm happy to add it.

**Comment by rhishikeshj** [comment]
Hey @Mike-Gibson , thank you for getting back so quickly ! :)
Yes your solution also works for me :) I hadn't thought about this actually.
Now that you have written it, it seems very obvious ! :D

**Comment by Mike-Gibson** [comment]
Glad to hear it works 🙂

**Comment by m0rtalis** [comment]
Hey @Mike-Gibson, the solution works for me too but if you ever come around implementing the `clearRequestHandlers ` method I would appreciate it. That way I can just add it to a `beforeEach` method in jest. It would be easier than having to handle multiple mocks for different queries.

**Comment by Mike-Gibson** [comment]
Thanks for the feedback @m0rtalis 

I will take a look at adding a clear method.

**Comment by jBernavaPrah** [comment]
Hi @Mike-Gibson, 
I'd also appreciate the clearRequestHandlers method.
