### ISSUE TITLE
How to handle the error states?

### ISSUE THREAD

**Issue by sschneider-ihre-pvs** [Mike-Gibson/mock-apollo-client#41]
I am trying to test the error states of the mocked client but I seem to be unable to catch or expect. How would I catch errors either from throws within the client or network ?

**Comment by Mike-Gibson** [comment]
Hi,

Have you come across [Error States](https://github.com/Mike-Gibson/mock-apollo-client#error-states) in the README? 

After that, the error should be available to whatever is using the result of the query.

Are you able to share the code you are using in your test, and where you're trying to test when the query errors? Maybe I can help more with some code.

**Comment by sschneider-ihre-pvs** [comment]
I guess I found the problem but I will share the code anyway
So trying to being smart I did this :)
```typescript
const successQueryHandler: any = jest
  .fn()
  .mockReturnValue(Promise.resolve());

const errorQueryHandler: any = jest
   .fn()
   .mockReturnValue(Promise.reject(new Error('GraphQL Network Error'))
);
```
which then immediatly fired the error
instead, this seems to work
```typescript
const successQueryHandler: any = jest
  .fn()
  .mockReturnValue(Promise.resolve());

const errorQueryHandler: any = jest.fn(() =>
  Promise.reject(new Error('GraphQL Network Error'))
);
```

**Comment by Mike-Gibson** [comment]
Glad you resolved the problem!

Please feel free to ask any other questions you have while using the library. Always happy to help, and it's useful in case anything in the API or README can be improved.

As an aside, I tend to use `mockResolvedValue` and `mockRejectedValue`, the latter of which is equivalent to what you changed your error handler to be.
