### ISSUE TITLE
Add typename

### ISSUE THREAD

**Issue by baleeds** [Mike-Gibson/mock-apollo-client#8]
This library looks very clean! 

I see your comment about handling `addTypename`, and I'm wondering what exactly needs to be done for that?  As it stands I'm getting plenty of warnings in my testing output from not specifying `__typename` in my queries.

If I change `addTypename` to true in `mock-apollo-client` then my tests fail.

**Comment by Mike-Gibson** [comment]
Thanks for using the library.

Yeah, I've previously had issues with addTypename too. The [official docs describe the issue](https://www.apollographql.com/docs/react/development-testing/testing/#addtypename) quite well.

I think I'd need to extend the tests to check what the behaviour currently is, and how the setting affects the queries and the cache. I think the way the mockLink matches requests to handlers would then need to be changed. I'm not 100% sure though.

What errors/warnings do you get when addTypename is false?

**Comment by Mike-Gibson** [comment]
Hi @baleeds, just wondering if this is still an issue for you?

**Comment by Mike-Gibson** [comment]
Closing for now. Please feel free to re-open if you think it's still an issue. 
Now ApolloClient constructor options can be passed in, I think the behaviour can be customised better for each project's set up.
